# Generated by Django 3.1.4 on 2020-12-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('course_image', models.ImageField(upload_to='files/courseimage')),
            ],
        ),
    ]
