# Generated by Django 3.1.4 on 2020-12-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_coursess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coursess',
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='course_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='course_image',
            field=models.ImageField(upload_to='files/course'),
        ),
    ]
