# Generated by Django 3.1.4 on 2020-12-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20201231_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='course_id',
            field=models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
