# Generated by Django 3.1.4 on 2020-12-31 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20201231_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.coursecategory'),
            preserve_default=False,
        ),
    ]
