# Generated by Django 3.1.4 on 2021-01-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20210102_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='resourse',
            field=models.FileField(null=True, upload_to='files/video/resourse'),
        ),
    ]
