# Generated by Django 3.1.4 on 2021-01-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20210102_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='caption',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
