# Generated by Django 3.1.4 on 2021-01-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20210103_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default='No', null=True),
        ),
    ]
