# Generated by Django 3.1.4 on 2021-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20210103_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
