# Generated by Django 3.1.4 on 2021-01-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20210103_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='resourse',
            field=models.FileField(blank=True, null=True, upload_to='files/resourse'),
        ),
    ]
