# Generated by Django 3.1.4 on 2021-01-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
