# Generated by Django 3.1.4 on 2021-05-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_course_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
