# Generated by Django 3.1.4 on 2021-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_course_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
