# Generated by Django 3.1.4 on 2021-05-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_auto_20210522_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='course_description',
        ),
    ]
