# Generated by Django 3.1.4 on 2021-05-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_auto_20210526_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.FileField(upload_to='files/videos'),
        ),
    ]
