# Generated by Django 3.1.4 on 2021-05-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_auto_20210526_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
