# Generated by Django 3.1.4 on 2021-01-15 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('usercourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usercourse.usercourse'),
        ),
    ]
