# Generated by Django 3.1.4 on 2021-05-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorapply',
            old_name='video_expect',
            new_name='video_expert',
        ),
    ]
